from commands import *


load(0x8000, "slices/bank3.bin", "6502")

config.set_lower_case(False)

# Remove all extras
config.set_label_references(False)
config.set_show_autogenerated_labels(False)
config.set_show_all_labels(False)
config.set_inline_comment_column(50)
config.set_subroutine_header("*" * 78)

entry(0x8000)
string(0x8007, 5)
string(0x800C, 0x8053 - 0x800C)

byte(0x8053, 0x95CE - 0x8053)

byte(0x95CE, 0xA7B6 - 0x95CE)

entry(0xA7B6)
entry(0xA7B7)
entry(0xA9D1)
entry(0xAABC)
entry(0xABE7)
entry(0xAC1D)
entry(0xAD43)
entry(0xAFC3)
entry(0xAFC8)
entry(0xAFCD)
entry(0xB0E1)
entry(0xB18E)
entry(0xB219)
entry(0xB2BC)
entry(0xB2FB)
entry(0xB341)
entry(0xB5F6)
entry(0xB63D)
entry(0xB673)
entry(0xB9E2)
entry(0xBA11)
entry(0xBA23)

exec(open('py8dis-scripts/common-variables.py').read())

go()
