from commands import *


load(0x8000, "slices/bank5.bin", "6502")

config.set_lower_case(False)

# Remove all extras
config.set_label_references(False)
config.set_show_autogenerated_labels(False)
config.set_show_all_labels(False)
config.set_inline_comment_column(50)
config.set_subroutine_header("*" * 78)
config.set_indent_string(" ")

entry(0x8000)
string(0x8007, 5)

byte(0x800C, 0xBEDA - 0x800C)
hexadecimal(0x800C, 0xBEDA - 0x800C)

entry(0xBEDA)
entry(0xBEEA)
entry(0xBF41)

byte(0xBF64, 4)
hexadecimal(0xBF64, 4)

exec(open('py8dis-scripts/common-variables.py').read())

go()
