from commands import *


load(0x8000, "slices/bank4.bin", "6502")

config.set_lower_case(False)

# Remove all extras
config.set_label_references(False)
config.set_show_autogenerated_labels(False)
config.set_show_all_labels(False)
config.set_inline_comment_column(46)
config.set_subroutine_header("*" * 78)
config.set_indent_string(" ")

entry(0x8000)
string(0x8007, 5)

byte(0x800C, 0xB8F9 - 0x800C)
hexadecimal(0x800C, 0xB8F9 - 0x800C)

entry(0xB8F9)
entry(0xB93C)
entry(0xB96B)
entry(0xB9F9)
entry(0xB9F9)

subroutine(0xB8F9, "subm_B8F9")
subroutine(0xB93C, "subm_B93C")
subroutine(0xB96B, "subm_B96B")
subroutine(0xB9C1, "subm_B9C1")
subroutine(0xB9F9, "subm_B9F9")

exec(open('py8dis-scripts/common-variables.py').read())

go()
